default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: collabsphere_development
  username: collabsphere
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: collabsphere_test
  username: collabsphere
  password: password
  host: localhost
  port: 5432

production:
  primary: &primary_production
    <<: *default
    database: collabsphere_production
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    host: localhost
  cache:
    <<: *primary_production
    database: collabsphere_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: collabsphere_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: collabsphere_production_cable
    migrations_paths: db/cable_migrate
